"""公众号排版主题 — 移植自 md-to-weixin（EvoAI-li）。

每个主题是一组字面量 CSS 变量（公众号不支持 ``var()``），外加 Pygments
配色风格名（用于代码块高亮）。新增主题只需在此追加一个 dict 并在
``get_theme`` 的索引中注册。
"""

from __future__ import annotations

from typing import Dict, List

#: Pygments 内置风格名 → 适用场景（浅色 / 深色代码块背景）。
_PYGMENTS_DARK = "native"
_PYGMENTS_LIGHT = "friendly"

THEMES: List[Dict[str, object]] = [
    {
        "id": "default",
        "name": "微信默认",
        "emoji": "⬜",
        "pygments_style": "default",
        "vars": {
            "--body-bg": "#ffffff",
            "--body-padding": "20px",
            "--text-color": "#333333",
            "--text-size": "15px",
            "--line-height": "1.8",
            "--font-family": '-apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
            "--primary": "#07c160",
            "--h1-size": "24px",
            "--h1-color": "#1a1a1a",
            "--h1-weight": "700",
            "--h1-border-bottom": "2px solid #07c160",
            "--h1-padding-bottom": "10px",
            "--h2-size": "20px",
            "--h2-color": "#1a1a1a",
            "--h2-weight": "700",
            "--h2-border-left": "4px solid #07c160",
            "--h2-padding-left": "12px",
            "--h3-size": "17px",
            "--h3-color": "#333333",
            "--h3-weight": "700",
            "--strong-color": "#07c160",
            "--em-color": "#555555",
            "--a-color": "#07c160",
            "--blockquote-bg": "#f9f9f9",
            "--blockquote-border": "#07c160",
            "--blockquote-color": "#666666",
            "--code-bg": "#f6f8fa",
            "--code-color": "#d73a49",
            "--code-border": "#e1e4e8",
            "--pre-bg": "#f6f8fa",
            "--pre-color": "#24292e",
            "--table-header-bg": "#07c160",
            "--table-header-color": "#ffffff",
            "--table-border": "#e0e0e0",
            "--table-row-even": "#f9f9f9",
            "--hr-color": "#e0e0e0",
        },
    },
    {
        "id": "tech-blue",
        "name": "科技蓝",
        "emoji": "🔵",
        "pygments_style": _PYGMENTS_DARK,
        "vars": {
            "--body-bg": "#f0f7ff",
            "--body-padding": "20px",
            "--text-color": "#1a2a4a",
            "--text-size": "15px",
            "--line-height": "1.8",
            "--font-family": '"Helvetica Neue", Arial, "PingFang SC", "Microsoft YaHei", sans-serif',
            "--primary": "#1e88e5",
            "--h1-size": "24px",
            "--h1-color": "#0d47a1",
            "--h1-weight": "700",
            "--h1-border-bottom": "2px solid #1e88e5",
            "--h1-padding-bottom": "10px",
            "--h2-size": "20px",
            "--h2-color": "#0d47a1",
            "--h2-weight": "700",
            "--h2-border-left": "4px solid #1e88e5",
            "--h2-padding-left": "12px",
            "--h3-size": "17px",
            "--h3-color": "#1565c0",
            "--h3-weight": "700",
            "--strong-color": "#1565c0",
            "--em-color": "#1e88e5",
            "--a-color": "#1e88e5",
            "--blockquote-bg": "#e3f2fd",
            "--blockquote-border": "#1e88e5",
            "--blockquote-color": "#1565c0",
            "--code-bg": "#e8f4fd",
            "--code-color": "#0d47a1",
            "--code-border": "#bbdefb",
            "--pre-bg": "#1a2a4a",
            "--pre-color": "#e3f2fd",
            "--table-header-bg": "#1e88e5",
            "--table-header-color": "#ffffff",
            "--table-border": "#bbdefb",
            "--table-row-even": "#e3f2fd",
            "--hr-color": "#90caf9",
        },
    },
    {
        "id": "literary",
        "name": "文艺清新",
        "emoji": "🌸",
        "pygments_style": _PYGMENTS_LIGHT,
        "vars": {
            "--body-bg": "#fdf6f0",
            "--body-padding": "20px",
            "--text-color": "#5c4a3a",
            "--text-size": "15px",
            "--line-height": "1.9",
            "--font-family": 'Georgia, "Times New Roman", "PingFang SC", "STSong", "SimSun", serif',
            "--primary": "#d4956a",
            "--h1-size": "24px",
            "--h1-color": "#8b5e3c",
            "--h1-weight": "700",
            "--h1-border-bottom": "1px solid #d4956a",
            "--h1-padding-bottom": "10px",
            "--h2-size": "20px",
            "--h2-color": "#8b5e3c",
            "--h2-weight": "700",
            "--h2-border-left": "4px solid #d4a574",
            "--h2-padding-left": "12px",
            "--h3-size": "17px",
            "--h3-color": "#7a5040",
            "--h3-weight": "700",
            "--strong-color": "#c0713a",
            "--em-color": "#a0785a",
            "--a-color": "#c0713a",
            "--blockquote-bg": "#fdf0e6",
            "--blockquote-border": "#d4a574",
            "--blockquote-color": "#8b6550",
            "--code-bg": "#fdf0e8",
            "--code-color": "#c0713a",
            "--code-border": "#e8c9aa",
            "--pre-bg": "#f5e6d8",
            "--pre-color": "#5c4a3a",
            "--table-header-bg": "#d4956a",
            "--table-header-color": "#ffffff",
            "--table-border": "#e8c9aa",
            "--table-row-even": "#fdf0e6",
            "--hr-color": "#e8c9aa",
        },
    },
    {
        "id": "dark",
        "name": "暗黑酷炫",
        "emoji": "🌑",
        "pygments_style": "monokai",
        "vars": {
            "--body-bg": "#1a1a2e",
            "--body-padding": "20px",
            "--text-color": "#c8d6e5",
            "--text-size": "15px",
            "--line-height": "1.8",
            "--font-family": '"JetBrains Mono", "Fira Code", Consolas, "PingFang SC", "Microsoft YaHei", monospace',
            "--primary": "#00d4ff",
            "--h1-size": "24px",
            "--h1-color": "#00d4ff",
            "--h1-weight": "700",
            "--h1-border-bottom": "1px solid #00d4ff",
            "--h1-padding-bottom": "10px",
            "--h2-size": "20px",
            "--h2-color": "#00d4ff",
            "--h2-weight": "700",
            "--h2-border-left": "4px solid #00d4ff",
            "--h2-padding-left": "12px",
            "--h3-size": "17px",
            "--h3-color": "#7ec8e3",
            "--h3-weight": "700",
            "--strong-color": "#00d4ff",
            "--em-color": "#7ec8e3",
            "--a-color": "#00d4ff",
            "--blockquote-bg": "#16213e",
            "--blockquote-border": "#00d4ff",
            "--blockquote-color": "#8a9bb0",
            "--code-bg": "#0f3460",
            "--code-color": "#00d4ff",
            "--code-border": "#1a4a8a",
            "--pre-bg": "#0d1117",
            "--pre-color": "#c9d1d9",
            "--table-header-bg": "#0f3460",
            "--table-header-color": "#00d4ff",
            "--table-border": "#1e3a5f",
            "--table-row-even": "#16213e",
            "--hr-color": "#1e3a5f",
        },
    },
    {
        "id": "green-forest",
        "name": "绿色森林",
        "emoji": "🌿",
        "pygments_style": _PYGMENTS_DARK,
        "vars": {
            "--body-bg": "#f0f7f0",
            "--body-padding": "20px",
            "--text-color": "#2d4a2d",
            "--text-size": "15px",
            "--line-height": "1.85",
            "--font-family": '-apple-system, BlinkMacSystemFont, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
            "--primary": "#4caf50",
            "--h1-size": "24px",
            "--h1-color": "#1b5e20",
            "--h1-weight": "700",
            "--h1-border-bottom": "2px solid #4caf50",
            "--h1-padding-bottom": "10px",
            "--h2-size": "20px",
            "--h2-color": "#1b5e20",
            "--h2-weight": "700",
            "--h2-border-left": "4px solid #4caf50",
            "--h2-padding-left": "12px",
            "--h3-size": "17px",
            "--h3-color": "#2e7d32",
            "--h3-weight": "700",
            "--strong-color": "#2e7d32",
            "--em-color": "#558b2f",
            "--a-color": "#2e7d32",
            "--blockquote-bg": "#e8f5e9",
            "--blockquote-border": "#4caf50",
            "--blockquote-color": "#33691e",
            "--code-bg": "#f1f8e9",
            "--code-color": "#1b5e20",
            "--code-border": "#c5e1a5",
            "--pre-bg": "#1b3a20",
            "--pre-color": "#c8e6c9",
            "--table-header-bg": "#4caf50",
            "--table-header-color": "#ffffff",
            "--table-border": "#c5e1a5",
            "--table-row-even": "#e8f5e9",
            "--hr-color": "#c5e1a5",
        },
    },
]

_THEME_INDEX: Dict[str, Dict[str, object]] = {t["id"]: t for t in THEMES}  # type: ignore[index]


def get_theme(theme_id: str) -> Dict[str, object]:
    """Return a theme by id (falls back to 微信默认)."""
    return _THEME_INDEX.get((theme_id or "").strip(), THEMES[0])


def theme_options() -> List[Dict[str, str]]:
    """Compact public shape for the UI (id / name / emoji)."""
    return [
        {"id": str(t["id"]), "name": str(t["name"]), "emoji": str(t["emoji"])}
        for t in THEMES
    ]
