"""Generate admin/routes.py with correct syntax."""
from pathlib import Path

C = ")"  # closing paren as variable so it cannot be stripped by accident

parts = []

def w(s: str = "") -> None:
    parts.append(s)

w('"""Admin console: login, dashboard, uploads, system."""')
w("from __future__ import annotations")
w()
w("import os")
w("from typing import Optional")
w("from urllib.parse import quote")
w()
w("from fastapi import APIRouter, Form, HTTPException, Query, Request")
w("from fastapi.responses import FileResponse, HTMLResponse, JSONResponse, RedirectResponse")
w("from fastapi.templating import Jinja2Templates")
w()
w("from admin.auth import (")
w("    check_password,")
w("    clear_session_cookie,")
w("    create_session_token,")
w("    is_admin,")
w("    require_admin,")
w("    set_session_cookie,")
w(C)
w("from storage import (")
w("    RETENTION_DAYS,")
w("    cleanup_expired,")
w("    delete_record,")
w("    get_record,")
w("    list_records,")
w("    resolve_stored,")
w("    storage_stats,")
w(C)
w("from tools import TOOL_REGISTRY, tools_by_category")
w()
w('router = APIRouter(prefix="/admin", tags=["admin"]' + C)
w()
w("BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))" + C + C)
w('templates = Jinja2Templates(directory=os.path.join(BASE_DIR, "templates")' + C + C)
w()
w()
w("def _tpl(request: Request, name: str, **ctx" + C + ":")
w("    data = {")
w('        "request": request,')
w('        "is_admin": is_admin(request' + C + ",")
w('        "app_version": "0.7.0",')
w("        **ctx,")
w("    }")
w("    return templates.TemplateResponse(request, name, data" + C)
w()
w()
w("def _safe_next(next_url: Optional[str]" + C + " -> str:")
w("    if not next_url:")
w('        return "/admin"')
w('    if next_url.startswith("/admin"' + C + ' and "://" not in next_url and "\\\\" not in next_url:')
w("        return next_url")
w('    return "/admin"')
w()
w()
w("def _build_health(" + C + " -> dict:")
w("    from word2pdf import engine_info")
w("    from converter import ocr_info")
w()
w("    w2p = engine_info(" + C)
w("    ocr = ocr_info(" + C)
w("    return {")
w('        "word2pdf": w2p,')
w('        "ocr": ocr,')
w('        "tools": len(TOOL_REGISTRY' + C + ",")
w('        "categories": len(tools_by_category(' + C + C + ",")
w("    }")
w()
w()
w('@router.get("/login", response_class=HTMLResponse' + C)
w("async def login_page(")
w("    request: Request,")
w("    next: Optional[str] = Query(None" + C + ",")
w("    error: Optional[str] = Query(None" + C + ",")
w(C + ":")
w("    if is_admin(request" + C + ":")
w("        return RedirectResponse(url=_safe_next(next" + C + ", status_code=303" + C)
w("    return _tpl(")
w("        request,")
w('        "admin/login.html",')
w("        next_url=_safe_next(next" + C + ",")
w("        error=error,")
w("    " + C)
w()
w()
w('@router.post("/login"' + C)
w("async def login_submit(")
w("    request: Request,")
w("    password: str = Form(..." + C + ",")
w("    next: Optional[str] = Form(None" + C + ",")
w(C + ":")
w("    if not check_password(password" + C + ":")
w('        dest = "/admin/login?error=" + quote("password error"' + C + ' + "&next=" + quote(_safe_next(next' + C + C)
w("        return RedirectResponse(url=dest, status_code=303" + C)
w("    resp = RedirectResponse(url=_safe_next(next" + C + ", status_code=303" + C)
w("    set_session_cookie(resp, create_session_token(" + C + C)
w("    return resp")
w()
w()
w('@router.post("/logout"' + C)
w("async def logout(" + C + ":")
w('    resp = RedirectResponse(url="/admin/login", status_code=303' + C)
w("    clear_session_cookie(resp" + C)
w("    return resp")
w()
w()
w('@router.get("/logout"' + C)
w("async def logout_get(" + C + ":")
w('    resp = RedirectResponse(url="/admin/login", status_code=303' + C)
w("    clear_session_cookie(resp" + C)
w("    return resp")
w()
w()
w('@router.get("", response_class=HTMLResponse' + C)
w('@router.get("/", response_class=HTMLResponse' + C)
w("async def dashboard(request: Request" + C + ":")
w("    redir = require_admin(request" + C)
w("    if redir:")
w("        return redir")
w("    return _tpl(")
w("        request,")
w('        "admin/dashboard.html",')
w('        active="dashboard",')
w("        stats=storage_stats(" + C + ",")
w("        health=_build_health(" + C + ",")
w("        recent=list_records(limit=8" + C + ",")
w("        tools=TOOL_REGISTRY,")
w("        categories=tools_by_category(" + C + ",")
w("    " + C)
w()
w()
w('@router.get("/uploads", response_class=HTMLResponse' + C)
w("async def uploads_page(")
w("    request: Request,")
w("    tool: Optional[str] = Query(None" + C + ",")
w("    q: Optional[str] = Query(None" + C + ",")
w("    limit: int = Query(100, ge=1, le=200" + C + ",")
w(C + ":")
w("    redir = require_admin(request" + C)
w("    if redir:")
w("        return redir")
w("    items = list_records(limit=limit" + C)
w('    tool_f = (tool or "").strip(' + C)
w('    q_f = (q or "").strip(' + C + ".lower(" + C)
w("    if tool_f:")
w('        items = [r for r in items if r.get("tool"' + C + " == tool_f]")
w("    if q_f:")
w("        items = [")
w("            r")
w("            for r in items")
w('            if q_f in str(r.get("original_name"' + C + ' or "").lower(' + C)
w('            or q_f in str(r.get("id"' + C + ' or "").lower(' + C)
w("        ]")
w("    tools_used = sorted(")
w('        {str(r.get("tool"' + C + ' or "") for r in list_records(limit=200' + C + ' if r.get("tool"' + C + "}")
w("    " + C)
w("    return _tpl(")
w("        request,")
w('        "admin/uploads.html",')
w('        active="uploads",')
w("        items=items,")
w("        tool_filter=tool_f,")
w('        q=q or "",')
w("        tools_used=tools_used,")
w("        retention_days=RETENTION_DAYS,")
w('        flash=request.query_params.get("msg"' + C + ",")
w("    " + C)
w()
w()
w('@router.post("/uploads/{record_id}/delete"' + C)
w("async def uploads_delete(request: Request, record_id: str" + C + ":")
w("    redir = require_admin(request" + C)
w("    if redir:")
w("        return redir")
w("    ok = delete_record(record_id" + C)
w('    msg = "deleted" if ok else "not found"')
w('    return RedirectResponse(url="/admin/uploads?msg=" + quote(msg' + C + ", status_code=303" + C)
w()
w()
w('@router.get("/uploads/{record_id}/download"' + C)
w("async def uploads_download(request: Request, record_id: str" + C + ":")
w("    redir = require_admin(request" + C)
w("    if redir:")
w("        return redir")
w("    rec = get_record(record_id" + C)
w("    if not rec:")
w('        raise HTTPException(status_code=404, detail="Record not found"' + C)
w('    rel = rec.get("input_rel"' + C)
w("    if not rel:")
w('        raise HTTPException(status_code=404, detail="No file"' + C)
w("    path = resolve_stored(str(rel" + C + C)
w("    if path is None:")
w('        raise HTTPException(status_code=404, detail="File missing"' + C)
w('    name = rec.get("original_name"' + C + " or path.name")
w("    return FileResponse(path, filename=str(name" + C + C)
w()
w()
w('@router.post("/cleanup"' + C)
w("async def run_cleanup(request: Request" + C + ":")
w("    redir = require_admin(request" + C)
w("    if redir:")
w("        return redir")
w("    removed = cleanup_expired(" + C)
w('    msg = "cleaned %d" % removed')
w('    return RedirectResponse(url="/admin/uploads?msg=" + quote(msg' + C + ", status_code=303" + C)
w()
w()
w('@router.get("/system", response_class=HTMLResponse' + C)
w("async def system_page(request: Request" + C + ":")
w("    redir = require_admin(request" + C)
w("    if redir:")
w("        return redir")
w("    return _tpl(")
w("        request,")
w('        "admin/system.html",')
w('        active="system",')
w("        health=_build_health(" + C + ",")
w("        stats=storage_stats(" + C + ",")
w("        tools=TOOL_REGISTRY,")
w("        categories=tools_by_category(" + C + ",")
w("        env_hints={")
w('            "ADMIN_PASSWORD": "set" if os.environ.get("ADMIN_PASSWORD"' + C + ' else "default admin123",')
w('            "UPLOAD_RETENTION_DAYS": str(RETENTION_DAYS' + C + ",")
w('            "UPLOAD_FILE_DIR": os.environ.get("UPLOAD_FILE_DIR"' + C + ' or "(default ./file)",')
w('            "LIBREOFFICE_PATH": os.environ.get("LIBREOFFICE_PATH"' + C + ' or "(auto)",')
w('            "PDF2WORD_OCR": os.environ.get("PDF2WORD_OCR"' + C + ' or "0",')
w("        },")
w("    " + C)
w()
w()
w('@router.get("/api/stats"' + C)
w("async def api_stats(request: Request" + C + ":")
w("    if not is_admin(request" + C + ":")
w('        raise HTTPException(status_code=401, detail="Unauthorized"' + C)
w('    return JSONResponse({"storage": storage_stats(' + C + ', "health": _build_health(' + C + "}" + C)
w()

text = "\n".join(parts) + "\n"
out = Path(__file__).resolve().parent / "routes.py"
out.write_text(text, encoding="utf-8")

import ast

try:
    ast.parse(text)
    print("PARSE_OK", out)
except SyntaxError as e:
    print("PARSE_FAIL", e)
    ls = text.splitlines()
    n = e.lineno or 1
    for i in range(max(1, n - 3), min(len(ls), n + 3) + 1):
        print(f"{i}: {ls[i-1]!r}")
